#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros -Q -- $0 "$@"
|#

(defpackage :git-done
  (:use :cl))
(in-package :git-done)

(defun run (command)
  "Run a shell command and return its stdout as a string."
  (uiop:run-program command
                     :output '(:string :stripped t)
                     :error-output :interactive))

(defun git-config (key)
  (ignore-errors (run (list "git" "config" key))))

(defun git-done-author ()
  (or (uiop:getenv "GIT_DONE_AUTHOR")
      (git-config "user.name")
      ""))

(defun parse-ref-line (line)
  "Parse a 'date<TAB>hash' line into (date . hash)."
  (let ((tab-pos (position #\Tab line)))
    (if tab-pos
        (cons (subseq line 0 tab-pos)
              (subseq line (1+ tab-pos)))
        (cons "" line))))

(defun commit-refs (author extra-args)
  "Return a list of commit hashes, sorted by date descending."
  (let* ((fmt (format nil "--pretty=%ad~C%H" #\Tab))
         (output (run `("git" "log"
                        ,(format nil "--author=~A" author)
                        ,fmt
                        "--date=iso"
                        "--no-merges"
                        ,@extra-args))))
    (when (and output (plusp (length output)))
      (let ((entries (mapcar #'parse-ref-line
                             (uiop:split-string output
                                                :separator '(#\Newline)))))
        (sort entries #'string> :key #'car)))))

(defun commit-subject (hash)
  (run (list "git" "log" "-1" "--pretty=%s" hash)))

(defun commit-date (hash)
  (run (list "git" "log" "-1" "--pretty=%ad" "--date=iso" hash)))

(defun commit-body (hash)
  (run (list "git" "log" "-1" "--pretty=%b" hash)))

(defun commit-patch (hash)
  (run (list "git" "diff-tree" "-p" "--no-commit-id" "--root" hash)))

(defun max-leading-run (char text)
  "Find the longest run of CHAR at the start of any line in TEXT."
  (let ((max-run 0))
    (dolist (line (uiop:split-string text :separator '(#\Newline)))
      (let ((run (or (position-if (lambda (c) (char/= c char)) line)
                     (length line))))
        (when (> run max-run)
          (setf max-run run))))
    max-run))

(defun max-consecutive-run (char text)
  "Find the longest consecutive run of CHAR anywhere in TEXT."
  (let ((max-run 0)
        (cur-run 0))
    (loop for c across text do
      (if (char= c char)
          (incf cur-run)
          (setf cur-run 0))
      (when (> cur-run max-run)
        (setf max-run cur-run)))
    max-run))

(defun fence-for (text)
  "Return a backtick fence long enough to wrap TEXT safely."
  (make-string (max 3 (1+ (max-consecutive-run #\` text))) :initial-element #\`))

(defun heading-for (text)
  "Return a # heading prefix long enough to stay above any # in TEXT."
  (make-string (max 3 (1+ (max-leading-run #\# text))) :initial-element #\#))

(defun format-commit (hash)
  "Format a single commit as markdown."
  (let ((subject (commit-subject hash))
        (date (commit-date hash))
        (body (commit-body hash))
        (patch (commit-patch hash)))
    (let ((heading (heading-for (if body (format nil "~A~%~A" subject body) subject)))
          (fence (fence-for patch)))
      (with-output-to-string (s)
        (format s "~A ~A~%~%**~A** `~A`~%" heading subject date hash)
        (when (and body (plusp (length body)))
          (format s "~%~A~%" body))
        (format s "~%~Adiff~%~A~%~A" fence patch fence)))))

(defun main (&rest argv)
  (let* ((author (git-done-author))
         (refs (commit-refs author argv)))
    (dolist (ref refs)
      (let ((hash (cdr ref)))
        (write-string (format-commit hash))
        (terpri)
        (terpri)))))
;;; vim: set ft=lisp lisp:
